# @package agent
_target_: agent.semdice.SEMDICEAgent
name: semdice
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 256
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 1024 # 256 for pixels
init_critic: true
update_encoder: ${update_encoder}

alpha: 0.5
f_type: softchisq
actor_num_components: 5
nu_penalty_lambda: 0
nu_gp_threshold: 100
mu_penalty_lambda: 0
mu_gp_threshold: 1

use_icm: false
icm_rep_dim: 50

f_divergence_target: 0.1

p_init_data: false
mu_rand_inter: false
